import { afterEach, describe, expect, it, vi } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { importClaudeCode } from "../src/importers/claude-code.js";
import { listFiles } from "../src/core/forge.js";

/**
 * Empty-Forge identity (spec 10 §10.4, AC 3): importing the synthetic `acme-portal` workspace
 * into an empty Forge writes exactly the committed snapshot, which was generated by the 0.5.0
 * importer before template-aware import changed it. The date in the profile's description is
 * fixed, so the bytes are reproducible.
 *
 * Regenerate only with the user's confirmation, and review the diff like code:
 *   CRAFTAR_REGEN_GOLDEN_IMPORT=1 npx vitest run test/golden-import.test.ts
 */
const GOLDEN = path.resolve(__dirname, "golden");
const WORKSPACE = path.join(GOLDEN, "acme-portal");
const EXPECTED = path.join(GOLDEN, "import-acme-portal-expected");
const FIXED = new Date("2026-09-26T12:00:00Z");

const cleanups: Array<() => Promise<void>> = [];
afterEach(async () => {
  vi.useRealTimers();
  while (cleanups.length) await cleanups.pop()!();
});

async function snapshot(dir: string): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  for (const rel of await listFiles(dir)) out[rel] = (await fs.readFile(path.join(dir, rel))).toString("base64");
  return out;
}

async function importIntoEmptyForge(): Promise<string> {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "craftar-golden-import-"));
  cleanups.push(() => fs.rm(tmp, { recursive: true, force: true }));
  const ws = path.join(tmp, "acme-portal");
  for (const rel of await listFiles(WORKSPACE)) {
    await fs.mkdir(path.dirname(path.join(ws, rel)), { recursive: true });
    await fs.copyFile(path.join(WORKSPACE, rel), path.join(ws, rel));
  }
  const forge = path.join(tmp, "forge");
  vi.useFakeTimers({ toFake: ["Date"] });
  vi.setSystemTime(FIXED);
  await importClaudeCode({ workspaceRoot: ws, forgeRoot: forge, profileName: "acme-portal" });
  vi.useRealTimers();
  return forge;
}

describe("golden: import into an empty Forge (spec 10 §10.4)", () => {
  it("writes exactly the committed snapshot", async () => {
    const forge = await importIntoEmptyForge();
    if (process.env.CRAFTAR_REGEN_GOLDEN_IMPORT) {
      await fs.rm(EXPECTED, { recursive: true, force: true });
      for (const rel of await listFiles(forge)) {
        await fs.mkdir(path.dirname(path.join(EXPECTED, rel)), { recursive: true });
        await fs.copyFile(path.join(forge, rel), path.join(EXPECTED, rel));
      }
    }
    expect(await listFiles(forge)).toEqual(await listFiles(EXPECTED));
    expect(await snapshot(forge)).toEqual(await snapshot(EXPECTED));
  });
});
