import { appliesTo, outName, ruleFile, textFile } from "./shared.js";
import type { Emitter } from "./types.js";

/**
 * AGENTS.md target (open standard read by Codex, Cursor, Warp, Copilot, Kiro, Kimi…).
 * Concatenates the `always` rules into one file. Scoped rules (`fileMatch`, `manual`, `auto`)
 * are either listed with a path (when `claude-code` or `kiro` writes them) or embedded in full
 * (when no target writes them), so agents that only read AGENTS.md see every convention (spec 14).
 */
export const agentsMd: Emitter = {
  target: "agents-md",
  async emit(ctx) {
    const aimed = ctx.resolution.ingredients.filter((i) => appliesTo(i.meta.targets, "agents-md"));
    // AGENTS.md renders rules only; anything else aimed at this target is said out loud, never dropped silently.
    // One line per type, naming every ref: the default `targets: "*"` aims a whole profile here, and one
    // line per ingredient would bury the warnings that matter.
    const skipped = new Map<string, string[]>();
    for (const ing of aimed) {
      if (ing.meta.type !== "rule") skipped.set(ing.meta.type, [...(skipped.get(ing.meta.type) ?? []), ing.ref]);
    }
    for (const [type, refs] of skipped) {
      ctx.warn(`agents-md: ${refs.length} ${type} ingredient(s) have no AGENTS.md equivalent — skipped: ${refs.join(", ")}`);
    }
    const rules = aimed.filter((i) => i.meta.type === "rule");
    if (!rules.length) return [];
    const parts: string[] = [
      "<!-- GENERATED by craftar from the Forge. Edit the rule ingredients, not this file. -->",
      "",
      `# AGENTS.md — ${ctx.resolution.profile.name}`,
      "",
      "Conventions for coding agents working in this workspace. Sections below are the always-on rules;",
      "scoped rules are listed at the end with the paths they apply to.",
      "",
    ];
    const pathLines: string[] = [];
    const embedded: string[] = [];
    for (const ing of rules) {
      if (ing.meta.type !== "rule") continue;
      const body = (await ctx.text(ing, ing.meta.file)).replace(/\n+$/, "");
      if (ing.meta.inclusion === "always") {
        parts.push(`<!-- rule: ${outName(ing.meta)} -->`, body, "");
      } else {
        // Spec 14 §4.1: decide which target writes this rule file
        const writers = (["claude-code", "kiro"] as const).filter(
          (t) => ctx.resolution.targets.includes(t) && appliesTo(ing.meta.targets, t),
        );
        const scopeText =
          ing.meta.inclusion === "fileMatch"
            ? `applies to \`${[ing.meta.fileMatchPattern].flat().join("`, `")}\``
            : ing.meta.inclusion;
        if (writers.includes("claude-code")) {
          pathLines.push(`- \`${ruleFile("claude-code", ing.meta)}\` — ${scopeText}`);
        } else if (writers.includes("kiro")) {
          pathLines.push(`- \`${ruleFile("kiro", ing.meta)}\` — ${scopeText}`);
        } else {
          // State C: no target writes the rule file; embed it
          embedded.push(`<!-- rule: ${outName(ing.meta)} -->`, `> Scoped rule — ${scopeText}`, "", body, "");
        }
      }
    }
    if (pathLines.length || embedded.length) {
      parts.push("## Scoped rules", "", ...pathLines);
      if (pathLines.length) parts.push("");
      parts.push(...embedded);
    }
    return [await textFile(ctx, "AGENTS.md", parts.join("\n"), "agents-md", "rule/*")];
  },
};
