import { appliesTo, buildRuleLookup, outName, resolveRuleRefs, ruleFile, ruleWriter, textFile, type RefReport } from "./shared.js";
import type { Emitter } from "./types.js";

/**
 * AGENTS.md target (open standard read by Codex, Cursor, Warp, Copilot, Kiro, Kimi…).
 * Concatenates the `always` rules into one file. Scoped rules (`fileMatch`, `manual`, `auto`)
 * are either listed with a path (when `claude-code` or `kiro` writes them) or embedded in full
 * (when no target writes them), so agents that only read AGENTS.md see every convention (spec 14).
 */
export const agentsMd: Emitter = {
  target: "agents-md",
  async emit(ctx) {
    const aimed = ctx.resolution.ingredients.filter((i) => appliesTo(i.meta.targets, "agents-md"));
    // AGENTS.md renders rules only; anything else aimed at this target is said out loud, never dropped silently.
    // One line per type, naming every ref: the default `targets: "*"` aims a whole profile here, and one
    // line per ingredient would bury the warnings that matter.
    const skipped = new Map<string, string[]>();
    for (const ing of aimed) {
      if (ing.meta.type !== "rule") skipped.set(ing.meta.type, [...(skipped.get(ing.meta.type) ?? []), ing.ref]);
    }
    for (const [type, refs] of skipped) {
      ctx.warn(`agents-md: ${refs.length} ${type} ingredient(s) have no AGENTS.md equivalent — skipped: ${refs.join(", ")}`);
    }
    const rules = aimed.filter((i) => i.meta.type === "rule");
    if (!rules.length) return [];

    // Build the lookup once per AGENTS.md, not once per body (spec 15 §4.2)
    const lookup = buildRuleLookup(ctx.resolution.ingredients);

    const parts: string[] = [
      "<!-- GENERATED by craftar from the Forge. Edit the rule ingredients, not this file. -->",
      "",
      `# AGENTS.md — ${ctx.resolution.profile.name}`,
      "",
      "Conventions for coding agents working in this workspace. Sections below are the always-on rules;",
      "scoped rules are listed at the end with the paths they apply to.",
      "",
    ];
    const pathLines: string[] = [];
    const embedded: string[] = [];
    // Collect reports in AGENTS.md order: always-on first, then embedded (spec 15 §4.5)
    const alwaysReports: RefReport[] = [];
    const embeddedReports: RefReport[] = [];
    for (const ing of rules) {
      if (ing.meta.type !== "rule") continue;
      const rawBody = await ctx.text(ing, ing.meta.file);
      if (ing.meta.inclusion === "always") {
        // Resolve references, then trim trailing newlines (spec 15: after ctx.text, before the trim)
        const { text: resolved, report } = resolveRuleRefs(rawBody, ing.ref, lookup, ctx.resolution.targets);
        alwaysReports.push(report);
        const body = resolved.replace(/\n+$/, "");
        parts.push(`<!-- rule: ${outName(ing.meta)} -->`, body, "");
      } else {
        // Spec 14 §4.1: decide which target writes this rule file
        const writer = ruleWriter(ctx.resolution.targets, ing.meta.targets);
        const scopeText =
          ing.meta.inclusion === "fileMatch"
            ? `applies to \`${[ing.meta.fileMatchPattern].flat().join("`, `")}\``
            : ing.meta.inclusion;
        if (writer === "claude-code") {
          pathLines.push(`- \`${ruleFile("claude-code", ing.meta)}\` — ${scopeText}`);
        } else if (writer === "kiro") {
          pathLines.push(`- \`${ruleFile("kiro", ing.meta)}\` — ${scopeText}`);
        } else {
          // State C: no target writes the rule file; embed it
          // Resolve references in embedded bodies too (spec 15 §4, after ctx.text, before trim)
          const { text: resolved, report } = resolveRuleRefs(rawBody, ing.ref, lookup, ctx.resolution.targets);
          embeddedReports.push(report);
          const body = resolved.replace(/\n+$/, "");
          embedded.push(`<!-- rule: ${outName(ing.meta)} -->`, `> Scoped rule — ${scopeText}`, "", body, "");
        }
      }
    }
    if (pathLines.length || embedded.length) {
      parts.push("## Scoped rules", "", ...pathLines);
      if (pathLines.length) parts.push("");
      parts.push(...embedded);
    }

    // Emit the warning per spec 15 §4.5: at most one ctx.warn for AGENTS.md
    // Reports in AGENTS.md order: always-on first, then embedded
    emitRefWarning(ctx.warn, [...alwaysReports, ...embeddedReports]);

    return [await textFile(ctx, "AGENTS.md", parts.join("\n"), "agents-md", "rule/*")];
  },
};

/**
 * Emit the spec 15 §4.5 warning: one line with reworded rule references and/or dead .claude/ paths.
 * Deduplicates entries by (reference, citing) and (path, citing).
 */
function emitRefWarning(warn: (msg: string) => void, reports: RefReport[]): void {
  // Backstop only: each report covers one body, and resolveRuleRefs already dedups by (reference, citing ingredient).
  const rewordedSet = new Map<string, { ref: string; citing: string; kind: string }>();
  for (const r of reports) {
    for (const e of r.reworded) {
      const key = `${e.ref}|${e.citing}`;
      if (!rewordedSet.has(key)) rewordedSet.set(key, e);
    }
  }
  // Collect and deduplicate other paths by (path, citing)
  const othersSet = new Map<string, { path: string; citing: string }>();
  for (const r of reports) {
    for (const e of r.others) {
      const key = `${e.path}|${e.citing}`;
      if (!othersSet.has(key)) othersSet.set(key, e);
    }
  }

  const reworded = [...rewordedSet.values()];
  const others = [...othersSet.values()];

  if (!reworded.length && !others.length) return;

  const formatReworded = (entries: typeof reworded) =>
    entries.map((e) => `${e.ref} (in ${e.citing}; ${e.kind})`).join(", ");
  const formatOthers = (entries: typeof others) =>
    entries.map((e) => `${e.path} (in ${e.citing})`).join(", ");

  let msg = "";
  if (reworded.length) {
    msg = `agents-md: ${reworded.length} reference(s) to rule files this workspace does not have — reworded in AGENTS.md: ${formatReworded(reworded)}`;
    if (others.length) {
      msg += `; ${others.length} reference(s) to other .claude/ files it does not have — left as written: ${formatOthers(others)}`;
    }
  } else if (others.length) {
    msg = `agents-md: ${others.length} reference(s) to .claude/ files this workspace does not have — left as written: ${formatOthers(others)}`;
  }

  if (msg) warn(msg);
}
