import { appliesTo, outName, textFile } from "./shared.js";
import type { Emitter } from "./types.js";

/**
 * AGENTS.md target (open standard read by Codex, Cursor, Warp, Copilot, Kiro, Kimi…).
 * Concatenates the `always` rules into one file; `fileMatch`/`manual` rules are listed with their scope
 * so agents that only read AGENTS.md still know where the detailed conventions live.
 */
export const agentsMd: Emitter = {
  target: "agents-md",
  async emit(ctx) {
    const aimed = ctx.resolution.ingredients.filter((i) => appliesTo(i.meta.targets, "agents-md"));
    // AGENTS.md renders rules only; anything else aimed at this target is said out loud, never dropped silently.
    for (const ing of aimed) {
      if (ing.meta.type !== "rule") ctx.warn(`agents-md: ${ing.meta.type} ${ing.ref} has no AGENTS.md equivalent — skipped`);
    }
    const rules = aimed.filter((i) => i.meta.type === "rule");
    if (!rules.length) return [];
    const parts: string[] = [
      "<!-- GENERATED by craftar from the Forge. Edit the rule ingredients, not this file. -->",
      "",
      `# AGENTS.md — ${ctx.resolution.profile.name}`,
      "",
      "Conventions for coding agents working in this workspace. Sections below are the always-on rules;",
      "scoped rules are listed at the end with the paths they apply to.",
      "",
    ];
    const scoped: string[] = [];
    for (const ing of rules) {
      if (ing.meta.type !== "rule") continue;
      const body = (await ctx.text(ing, ing.meta.file)).replace(/\n+$/, "");
      if (ing.meta.inclusion === "always") {
        parts.push(`<!-- rule: ${outName(ing.meta)} -->`, body, "");
      } else {
        const scope = ing.meta.inclusion === "fileMatch" ? ` — applies to \`${[ing.meta.fileMatchPattern].flat().join("`, `")}\`` : ` — ${ing.meta.inclusion}`;
        scoped.push(`- \`.claude/rules/${outName(ing.meta)}.md\`${scope}`);
      }
    }
    if (scoped.length) parts.push("## Scoped rules", "", ...scoped, "");
    return [await textFile(ctx, "AGENTS.md", parts.join("\n"), "agents-md", "rule/*")];
  },
};
