import { afterEach, describe, expect, it } from "vitest";
import { loadWorkspace, plan, type Plan } from "../../src/core/sync.js";
import { profile, recipe, rule, scenario, type ForgeSpec, type IngredientSpec, type WorkspaceSpec } from "../helpers/forge.js";

const cleanups: Array<() => Promise<void>> = [];
afterEach(async () => {
  while (cleanups.length) await cleanups.pop()!();
});

async function planFor(ingredients: IngredientSpec[], files?: WorkspaceSpec["files"], targets = ["agents-md"]): Promise<Plan> {
  const forge: ForgeSpec = {
    ingredients,
    recipes: [recipe("base", ingredients.map((i) => `${i.meta.type}/${i.meta.name}`))],
    profiles: [profile("acme", ["base"], targets)],
  };
  const s = await scenario(forge, { config: { profile: "acme" }, files });
  cleanups.push(s.cleanup);
  return plan(await loadWorkspace(s.wsRoot));
}
const agentsMd = (p: Plan) => p.files.find((f) => f.path === "AGENTS.md")?.content.toString("utf8");

const HEADER = [
  "<!-- GENERATED by craftar from the Forge. Edit the rule ingredients, not this file. -->",
  "",
  "# AGENTS.md — acme",
  "",
  "Conventions for coding agents working in this workspace. Sections below are the always-on rules;",
  "scoped rules are listed at the end with the paths they apply to.",
  "",
];

describe("agents-md emitter", () => {
  it("concatenates always rules and lists scoped rules with their pattern", async () => {
    const p = await planFor([rule("a", "# A\n\nalways on\n"), rule("b", "# B\n", { inclusion: "fileMatch", fileMatchPattern: "projects/api/**" })]);
    const doc = agentsMd(p)!;
    expect(doc).toContain("<!-- rule: a -->\n# A\n\nalways on\n");
    expect(doc).toContain("## Scoped rules\n\n- `.claude/rules/b.md` — applies to `projects/api/**`\n");
    expect(doc).not.toContain("# B");
  });

  it("emits exactly these bytes for a fixed rule set", async () => {
    const p = await planFor([
      rule("style", "# Style\n\nUse two spaces.\n\n\n"),
      rule("api", "# API\n", { inclusion: "fileMatch", fileMatchPattern: ["projects/api/**", "projects/sdk/**"] }),
      rule("commits", "# Commits\n\nConventional Commits.\n"),
      rule("release", "# Release\n", { inclusion: "manual" }),
    ]);
    const expected = [
      ...HEADER,
      "<!-- rule: style -->",
      "# Style",
      "",
      "Use two spaces.",
      "",
      "<!-- rule: commits -->",
      "# Commits",
      "",
      "Conventional Commits.",
      "",
      "## Scoped rules",
      "",
      "- `.claude/rules/api.md` — applies to `projects/api/**`, `projects/sdk/**`",
      "- `.claude/rules/release.md` — manual",
      "",
    ].join("\n");
    expect(agentsMd(p)).toBe(expected);
    expect(p.files.map((f) => f.path)).toEqual(["AGENTS.md"]);
  });

  it("emits no AGENTS.md when no rule applies", async () => {
    const p = await planFor([rule("a", "# A\n", { targets: ["claude-code"] })], undefined, ["claude-code", "agents-md"]);
    expect(p.files.map((f) => f.path)).toEqual([".claude/rules/a.md"]);
  });

  it("names a variant by its original name, in the section marker and in the scoped list", async () => {
    const p = await planFor([
      rule("workflow--acme", "# W\n", { as: "workflow" }),
      rule("api--acme", "# API\n", { as: "api", inclusion: "fileMatch", fileMatchPattern: "projects/api/**" }),
    ]);
    const expected = [...HEADER, "<!-- rule: workflow -->", "# W", "", "## Scoped rules", "", "- `.claude/rules/api.md` — applies to `projects/api/**`", ""].join("\n");
    expect(agentsMd(p)).toBe(expected);
    expect(agentsMd(p)).not.toContain("--acme");
  });

  it("writes a new AGENTS.md with LF", async () => {
    const p = await planFor([rule("a", "# A\n\nbody\n")]);
    const doc = agentsMd(p)!;
    expect(doc).toBe([...HEADER, "<!-- rule: a -->", "# A", "", "body", ""].join("\n"));
    expect(doc).not.toContain("\r");
  });

  it("keeps the CRLF of the AGENTS.md it replaces", async () => {
    const p = await planFor([rule("a", "# A\n\nbody\n")], { "AGENTS.md": "# old\r\n" });
    expect(agentsMd(p)).toBe([...HEADER, "<!-- rule: a -->", "# A", "", "body", ""].join("\r\n"));
  });

  it("warns for a script aimed at agents-md instead of dropping it silently, and emits the same bytes", async () => {
    const script: IngredientSpec = { meta: { type: "script", name: "lint", files: ["lint.sh"], targets: ["agents-md"] }, files: { "lint.sh": "echo lint\n" } };
    const p = await planFor([rule("a", "# A\n\nbody\n"), script]);
    expect(p.warnings).toContain("agents-md: script script/lint has no AGENTS.md equivalent — skipped");
    expect(agentsMd(p)).toBe([...HEADER, "<!-- rule: a -->", "# A", "", "body", ""].join("\n"));
    expect(p.files.map((f) => f.path)).toEqual(["AGENTS.md"]);
  });

  it("warns for a non-rule aimed at agents-md even when there is no rule to emit", async () => {
    const p = await planFor([{ meta: { type: "mcp", name: "pw", server: { command: "npx" } } }]);
    expect(p.warnings).toContain("agents-md: mcp mcp/pw has no AGENTS.md equivalent — skipped");
    expect(p.files).toEqual([]);
  });

  it("does not warn for ingredients aimed away from agents-md", async () => {
    const p = await planFor(
      [
        rule("a", "# A\n"),
        { meta: { type: "script", name: "lint", files: ["lint.sh"], targets: ["claude-code"] }, files: { "lint.sh": "echo lint\n" } },
        { meta: { type: "steering", name: "product", file: "steering.md" }, files: { "steering.md": "# P\n" } },
      ],
      undefined,
      ["claude-code", "kiro", "agents-md"],
    );
    expect(p.warnings.filter((w) => w.startsWith("agents-md:"))).toEqual([]);
  });
});
